programa = 'Estas usando python' 
print(programa)
print('¿Como te llamas?')
nombre = input()
saludo = ('¡Hola, '+ nombre + ' ' + programa + '!')
print(saludo)
print(saludo.upper())
print(saludo.lower())
print(saludo.title())
print(saludo.replace('.',' ').title()) 